### PR TITLE
update example for type shorthands

### PR DESCRIPTION
**Pull request by janriemer**
When introducing type shorthands (aliases),
the types that are defined weren't used in the code example.

Add an example of how to use them.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Makes sense, the thing I did want to show in this chapter was inline "types" used as parameters - since they are both "type expressions".

**Comment by blakeembrey** [comment]
> In parameters, for instance, one can write an inline interface.

Do you think we could keep both perhaps?

**Comment by janriemer** [comment]
Good idea. Now, we have both!  :smirk:

**Comment by blakeembrey** [comment]
Cheers! :+1:

**Pull request merged**
